### ISSUE TITLE
OTA for GAPPLESS does not work

### ISSUE THREAD

**Issue by mamen** [LameMonster82/LineageOTAResponse#1]
The url in the judyln_nongapps.json file does not work. The response from the internet archive is:

> The item you have requested has a problem with one or more of the metadata files that describe it, which prevents us from displaying this page.
>
> Items may be taken down for various reasons, including by decision of the uploader or due to a violation of our Terms of Use. 

That may also be the reason, why my phone says that I have no internet connection when trying to download the OTA.

**Comment by LameMonster82** [comment]
That's because I forgot to rename the page where I uploaded the file. A temporary fix was pushed.
22089d09a5f7652c18d7ecad29d9b3f91dcd797c
